# Generated by Claude Sonnet 4.6 from prompt:
# Can you write code in plotnine in Python for generating a logistic curve.  I want to plot y = inv_logit(x) for x in (-6, 6).  I want a vertical axis line at x = 0, and another horizontal line at y = 0.5.  I want the code to render it to a pdf I can include in LaTeX for a slide, so the text should be relatively big compared to the size of the plot.  The axes should be labeled x and y and the title should say y = inv_logit(x).  The breaks on the y axis should be at 0, 0.25, 0.5, 0.75, and 1.  The x axis should be labeled with integers range(-6,7) in Python.

import numpy as np
import pandas as pd
import plotnine as pn

def inv_logit(x):
    return 1 / (1 + np.exp(-x))

x = np.linspace(-6, 6, 500)
y = inv_logit(x)
df = pd.DataFrame({"x": x, "y": y})

plot = (
    pn.ggplot(df, pn.aes(x="x", y="y"))
    + pn.geom_vline(xintercept=0, color="gray", linetype="dashed", size=0.7)
    + pn.geom_hline(yintercept=0.5, color="gray", linetype="dashed", size=0.7)
    + pn.geom_line(size=1.2, color="steelblue")
    + pn.scale_x_continuous(breaks=list(range(-6, 7)))
    + pn.scale_y_continuous(breaks=[0, 0.25, 0.5, 0.75, 1])
    + pn.labs(x="x", y="y", title="y = inv_logit(x)")
    + pn.theme_bw()
    + pn.theme(
        text=pn.element_text(size=16),
        plot_title=pn.element_text(size=20, ha="center"),
        axis_title=pn.element_text(size=18),
        axis_text=pn.element_text(size=14),
    )
)

plot.save("logistic_curve.pdf", width=6, height=4.5, units="in")
